author: John Fairhurst
author_url: http://github.com/johnfairh
copyright: Distributed under the MIT license.  Maintained by [John Fairhurst](mailto:johnfairh@gmail.com).
readme: README.md
products:
  - docs
code_host: github
code_host_url: https://github.com/johnfairh/swift-steamworks
code_host_file_url: https://github.com/johnfairh/swift-steamworks/blob/main
clean: true
sdk: macosx
theme: fw2020
deployment_url: https://johnfairh.github.io/swift-steamworks/
build_tool: spm
modules:
  - Steamworks
  - SteamworksHelpers
  - SteamworksEncryptedAppTicket
build_tool_arguments:
  - "-Xswiftc"
  - "-I${PWD}/sdk/public"
  - "-Xlinker"
  - "-lc++"
title: Steamworks v0.1.0
module_version: 0.1.0
topic_style: source-order-defs
hide_coverage: true
undocumented_text: ""
custom_groups:
  - name: API clients
    children:
      - SteamBaseAPI
      - SteamAPI
      - SteamGameServerAPI
      - SteamEncryptedAppTicket
  - name: Steamworks interfaces
    children:
      - filepath /Generated\/Steam.*swift/
  - name: Typealiases
    children:
      - filepath /Typedefs.swift/
      - SteamAPIWarningMessageHook
      - MatchMakingKeyValuePairs
  - name: Enumerations
    children:
      - filepath /Enums.swift/
  - name: Structures
    children:
      - filepath /Structs.swift/
      - filepath /ManualTypes.swift/
      - SteamID
      - GameID
  - name: Protocols
    children:
      - /Matchmaking.*Response/
  - name: Constants
    children:
      - SteamConstants
