name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  macos:
    name: macOS SPM unit tests
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          persist-credentials: false
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0-beta'
      - name: Set up SDK
        run: cd sdk && sudo make install
      - name: Run tests
        run: swift test

  macos_raw:
    name: macOS raw build
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          persist-credentials: false
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0-beta'
      - name: Raw build
        run: swift build
  
  linux:
    name: Linux SPM unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          persist-credentials: false
      - name: Set up SDK
        run: cd sdk && sudo make install
      - name: Run tests
        run: swift test -Xswiftc -cxx-interoperability-mode=default
