name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  macos:
    name: macOS SPM unit tests
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.0.app/Contents/Developer

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up SDK
        run: cd sdk && make install
      - name: Run tests
        run: swift test

  linux:
    name: Linux SPM unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up SDK
        run: cd sdk && sudo make install
      - name: Run tests
        run: swift test
