name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  macos:
    name: macOS SPM unit tests
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up SDK
        run: cd sdk && make install
      - name: Run tests
        run: swift test

  macos_raw:
    name: macOS raw build
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Raw build
        run: swift build
  
  linux:
    name: Linux SPM unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Give up and run in docker
        run: 'docker run -v `pwd`:`pwd` -w `pwd` --name steamworks --rm swiftlang/swift:nightly-5.9-focal /bin/bash -c "apt-get update; apt-get install make; (cd sdk && make install); swift test -Xswiftc -cxx-interoperability-mode=default"'
          #      - name: Set up SDK
          #run: cd sdk && sudo make install
          #- name: Run tests
          #run: swift test -Xswiftc -cxx-interoperability-mode=default
